### ISSUE TITLE
Definire un end point REST su standard OpenAPI

### ISSUE THREAD

**Issue by rasky** [italia/dati-frontendserver#1]
La definizione dei contratti di Front end potrebbe essere definita secondo lo standard definito
https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md

**Comment by giux78** [comment]
Utilizzo api-first-hand di zalando che e' utile nell'approccio contract first. Prima definisco gli endpoint e il modello dati di risposta secondo lo standard swagger 2.0. Poi la libreria trasforma il file conf/ftd_api.yaml in una applicativo play.
